services:
  web:
    
    image: php:8.1-apache
    container_name: indexfive_app
    restart: unless-stopped
    build: 
      context: .
    volumes:
      - ./Application:/var/www/html/Application                  
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./default-conf.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "80:80"
    environment:
      DB_HOST:     ${DB_HOST}
      DB_NAME:     ${DB_NAME}
      DB_USER:     ${DB_USER}
      DB_PASSWORD: ${DB_PASS}
